# Continues integration workflow to continuously check
# code quality and run tests before merging PRs
name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # Run code linter
  lint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@lazybytez'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_READ_NPM_TOKEN }}

      - name: Run code linters
        run: yarn lint
